### ISSUE TITLE
'tutorial' branch fails to run (missing GlobalStateManager)

### ISSUE THREAD

**Issue by h3r2tic** [spatialos/UnrealGDKThirdPersonShooter#42]
The 'tutorial' branch is the one referenced in [the Multiserver Shooter tutorial](https://docs.improbable.io/unreal/alpha/content/get-started/tutorial). It currently fails to run due to the missing unreal.GlobalStateManager component.

Similarly to the 'tutorial-complete' branch, 'tutorial' should apply the GlobalStateManager->SingletonManager rename.

**Comment by m-samiec** [comment]
@h3r2tic Thanks for reporting this. The issue is now fixed.

**Comment by h3r2tic** [comment]
Awesome, thank you :)
